site_name: passbook Docs
site_url: https://beryju.github.io/passbook
copyright: "Copyright &copy; 2019 - 2020 BeryJu.org"

nav:
  - Home: index.md
  - Installation:
    - Installation: installation/install.md
    - docker-compose: installation/docker-compose.md
    - Kubernetes: installation/kubernetes.md
  - Sources: sources.md
  - Providers: providers.md
  - Expressions:
    - Overview: expressions/index.md
    - Reference:
      - User Object: expressions/reference/user-object.md
  - Property Mappings:
    - Overview: property-mappings/index.md
    - Expressions: property-mappings/expression.md
  - Factors: factors.md
  - Policies:
    - Overview: policies/index.md
    - Expression: policies/expression.md
  - Integrations:
    - as Provider:
        - Amazon Web Services: integrations/services/aws/index.md
        - GitLab: integrations/services/gitlab/index.md
        - Rancher: integrations/services/rancher/index.md
        - Harbor: integrations/services/harbor/index.md
        - Sentry: integrations/services/sentry/index.md
        - Ansible Tower/AWX: integrations/services/tower-awx/index.md
  - Upgrading from v0.8.x: upgrading-from-0.8.x.md

repo_name: "BeryJu/passbook"
repo_url: https://github.com/BeryJu/passbook
theme:
  name: "material"
  logo: "images/logo.svg"

markdown_extensions:
  - toc:
      permalink: "¶"
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.inlinehilite
  - pymdownx.magiclink

plugins:
  - search
