apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "passbook.fullname" . }}-config
data:
  config.yml: |
    postgresql:
      host: "{{ .Release.Name }}-postgresql"
      name: "{{ .Values.postgresql.postgresqlDatabase }}"
      user: postgres
      {{- if .Values.backup }}
      backup:
        access_key: "{{ .Values.backup.access_key }}"
        secret_key: "{{ .Values.backup.secret_key }}"
        bucket: "{{ .Values.backup.bucket }}"
        host: "{{ .Values.backup.host }}"
      {{- end}}
    redis:
      host: "{{ .Release.Name }}-redis-master"
      cache_db: 0
      message_queue_db: 1
    error_reporting: {{ .Values.config.error_reporting }}
    log_level: "{{ .Values.config.log_level }}"
