trigger:
  - master

stages:
  - stage: lint
    jobs:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: GoTool@0
            inputs:
              version: '1.15'
          - task: Go@0
            inputs:
              command: 'get'
              arguments: '-u golang.org/x/lint/golint'
          - task: CmdLine@2
            inputs:
              script: '$(go list -f {{.Target}} golang.org/x/lint/golint) ./...'
              workingDirectory: 'proxy/'
  - stage: build_go
    jobs:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: GoTool@0
            inputs:
              version: '1.15'
          - task: Go@0
            inputs:
              command: 'build'
              workingDirectory: 'proxy/'
  - stage: build_docker
    jobs:
      - job: build_proxy
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'dockerhub'
            repository: 'beryju/passbook-proxy'
            command: 'buildAndPush'
            Dockerfile: 'proxy/Dockerfile'
            buildContext: 'proxy/'
            tags: 'gh-$(Build.SourceBranchName)'
