trigger:
  - master

stages:
  - stage: Lint
    jobs:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: GoTool@0
            inputs:
              version: '1.15'
          - task: Go@0
            inputs:
              command: 'get'
              arguments: '-u golang.org/x/lint/golint'
          - task: CmdLine@2
            inputs:
              script: 'golint ../...'
              workingDirectory: 'proxy/'
  - stage: Build
    jobs:
      - job:
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: GoTool@0
            inputs:
              version: '1.15'
          - task: Go@0
            inputs:
              command: 'build'
              workingDirectory: 'proxy/'
