name: passbook-ci-cleanup
on:
  - delete

jobs:
  delete-server:
    runs-on: ubuntu-latest
    steps:
      - name: Delete docker tag
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: curl
          -u $DOCKER_USERNAME:$DOCKER_PASSWORD
          -X "DELETE"
          "https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/passbook/tags/${GITHUB_REF##*/}/"
  delete-gatekeeper:
    runs-on: ubuntu-latest
    steps:
      - name: Delete docker tag
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: curl
          -u $DOCKER_USERNAME:$DOCKER_PASSWORD
          -X "DELETE"
          "https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/passbook-gatekeeper/tags/${GITHUB_REF##*/}/"
  delete-static:
    runs-on: ubuntu-latest
    steps:
      - name: Delete docker tag
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: curl
          -u $DOCKER_USERNAME:$DOCKER_PASSWORD
          -X "DELETE"
          "https://hub.docker.com/v2/repositories/$DOCKER_USERNAME/passbook-static/tags/${GITHUB_REF##*/}/"
